name: Tests && Linter

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install, build
        run: |
          make install
      - name: Run linter
        run: make lint
      - name: Tests
        run: npm run test
